version: 'v1'
services:
  # flask:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - db
  #     - kafka
  #   environment:
  #     - FLASK_APP=main.py
  #     - FLASK_ENV=development
  #     - POSTGRES_HOST=db
  #     - POSTGRES_PORT=5432
  #     - KAFKA_HOST=kafka
  #     - KAFKA_PORT=9092

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pritishsamal
      - POSTGRES_PASSWORD=Cymatics@7
      - POSTGRES_DB=orders

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - './zookeeper_data:/bitnami/zookeeper/data'
      - './zookeeper_logs:/bitnami/zookeeper/logs'

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - './kafka_data:/bitnami/kafka/data'
      - './kafka_logs:/bitnami/kafka/logs'