version: 'v1'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
      - kafka
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pritishsamal
      - POSTGRES_PASSWORD=Cymatics@7
      - POSTGRES_DB=orders

  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
